### ISSUE TITLE
TFVC: Error when trying to configure location

### ISSUE THREAD

**Issue by alelapeyre** [Microsoft/vsts-vscode#177]
Hi,

I'm trying to configure the TFVC location with the "tfvc.location" param but i have an error about TF executable langage. I also tried to install Team Explorer in English but I have the same error. Anyone have a workaround ?

**Settings**
- "tfvc.location": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TeamFoundation\\Team Explorer\\TF.exe"

**Error message**
![image](https://cloud.githubusercontent.com/assets/8047492/25038438/202c858e-20ff-11e7-9994-3f505f58207b.png)

**More info**
- Visual Studio Code - Version 1.11.2
- Visual Studio 2017
- Windows 8.1
- Team Foundation Server - Version 14.102.25423.0

**Comment by MindGirl** [comment]
I had the same problem when using a German version of Windows. My workaround:
In the same folder as tf.exe there are resource directories for the different cultures. I renamed the folder "de" (for German), so it could not find the localized resources. 

Hope this helps.

**Comment by jeffyoung** [comment]
Thanks for the tip @MindGirl!  Presumably if tf.exe doesn't find the resources (the "de" folder in your case since you renamed it), it'll fall back to English.

@alelapeyre, the TFVC extension has to parse the output from the various commands (like workspace, workfold, etc.) in order to get some of the information it needs to communicate with the server.  In some languages (German being one of them) the term 'workspace' is translated.  We made the choice to not 'chase' translations and decided to stick with English (at least for now).  In the macOS and Linux support, which uses Java, we can force the TEE CLC to proivde English results but there's no equivalent functionality with the Windows TF.exe version (we certainly looked).

**Comment by alelapeyre** [comment]
Thanks @MindGirl it works :). Thanks also @jeffyoung for the explanation.
