### ISSUE TITLE
Error: (team) Failed to find api location for area: core id: 603fe2ac-9723-48b9-88ad-09305aa6c6e1

### ISSUE THREAD

**Issue by gfrancischini** [Microsoft/vsts-vscode#212]
Visual Studio Code: 1.11.2
Extension Version: 1.117.1
TF: Visual Studio 2015

In Company Team foundation server: http://server_name:8080/tfs/defaultcollection

I´m able to view the modified files on the Source Control Viewlet but I cannot perfom diff command, history, or any other command exception Signin. 

Every command that a try throws the error:
(team) Failed to find api location for area: core id: 603fe2ac-9723-48b9-88ad-09305aa6c6e1

Sometimes I also get the message even if the path has a valid workspace and works on Visual Studio 2015:
(team) No Team Services or Team Foundation Server repository configuration was found. Ensure you've opened a folder that contains a repository.

**Comment by jeffyoung** [comment]
Hi @gfrancischini.  Thanks for trying out the extension.

Can you tell me the version of your Team Foundation Server?  That GUID corresponds to the "team project" endpoint which should be present in the last few versions of TFS.

On a TFS 2015 server (via web access), that information can be access via Help | About and it looks similar to this:

![image1](https://cloud.githubusercontent.com/assets/2796865/25722012/8a373154-30e0-11e7-92ce-b8c549c9f3fe.png)

**Comment by gfrancischini** [comment]
Hi @jeffyoung, thanks for your help

About Microsoft Visual Studio Team Foundation Server
Microsoft Visual Studio Team Foundation Server

Version 12.0.21005.1


So that means that I cannot run the extension right? I thought that my tf.exe should be 2015. 

There is any plan to support old tfs versions?

**Comment by jeffyoung** [comment]
In order to determine information about the server it needs to connect to, the extension makes calls to the TFS server to validate collection URLs, team project names, etc.  Those APIs weren't created until later versions of TFS.  IIRC, v12.0.21005.1 is a version of TFS 2013.  The extension itself (for some other reasons) requires TFS 2015 Update 2 (or later).

At this time, there aren't any plans to try and add support for earlier versions of TFS but I can attempt to make this condition more apparent in the UI (by providing a message about detecting an earlier version of TFS).  And you're correct in that you can do _some_ things with the extension but not others (although, ideally, with a TFS server that's too old, nothing should be enabled).  The extension basically has 2 parts: 1) the TFVC support (mostly, but not all, provided by tf.exe or the CLC), and 2) the Build/Work Item/Pull Request functionality (which mostly requires APIs to exist on the server).

**Comment by jeffyoung** [comment]
Hi @gfrancischini.

I looked into this issue for a bit and discovered that the version of your TFS server very likely is TFS 2013 RTM.  This error must be thrown from that version (and possibly even a few later updates) of TFS 2013.  The latest version of TFS 2013 appears to be Update 5 ([downloadable here](https://www.microsoft.com/en-us/download/details.aspx?id=48150)).  Based on the statement at the page, it appears TFS 2013 is no longer supported.

With a server running Update 5, it appears I can do all of the TFVC-related work that I tried (not really exhaustive).  Diffing a file did work as I expected.  History opened the browser to the wrong URL but got pointed to the root of the repository so you could navigate from there.

The one issue I did find was with with work item tracking (WIT). A WIT endpoint we rely upon is not available in Update 5 (while the core api you ran into must be because I didn't get the error you reported).  I'm working on a quick change to make handling the WIT error condition with Update 5 a little nicer. That error message is this:

`Failed to find api location for area: wit id: 1a9c53f7-f243-4447-b110-35ef023636e4`

So it is pretty familiar but specific to WIT.  Even if you didn't have my quick fix, using Update 5 would still work for TFVC and, I expect, for the Build functionality.  I'm not sure if you'd be able to update your server but thought I'd chime in with the information.  I may go back and see if I can catch the error you reported and make it more obvious what the issue is.

**Comment by gfrancischini** [comment]
Hi @jeffyoung , thank you for your feedback. Last week I started talking with our infrastructure team to upgrade the TFS but I think that will be easier to upgrade the TFS to Update 5 than migrating to a new version.

**Comment by jeffyoung** [comment]
OK, thanks for the information @gfrancischini.  BTW, are you using TFVC support or were you looking more for the Build/WIT features of the extension?

In the next version I publish (likely 1.118.1), you won't see this ugly message against RTM and if you update the server to Update 5, the WIT functionality will be "disabled" but the TFVC functionality should continue to work (if that's what you're using).

The "disabled" WIT functionality will look like this in the status bar (for polling):

![image](https://cloud.githubusercontent.com/assets/2796865/26208226/a0119208-3bb7-11e7-980f-15eb458f2bb8.png)

And look like this if you try to run a WIT-related command:

![image](https://cloud.githubusercontent.com/assets/2796865/26208281/ae9d14be-3bb7-11e7-8a8f-20f2ede9ced2.png)

I appreciate you taking the time to help with this.

**Comment by jeffyoung** [comment]
As of v1.118.1, this condition should now be detected and displayed as described in my previous response.  If a TFS 2013 RTM server is detected (core id not found), the extension won't initialize and a message indicating that TFS 2015 Update 2 or later is required will be displayed on hover in the status bar.  Thanks again @gfrancischini.
