### ISSUE TITLE
team.Reinitialize not found

### ISSUE THREAD

**Issue by tegaaa** [Microsoft/vsts-vscode#221]
This is still not working with latest code 1.12.1 and extension 1.117.3

**Comment by jeffyoung** [comment]
Do you have a folder opened in VS Code before you run the commands?  If not, I believe that's #204 (which I have a PR out to address).  But the extension requires that a folder is open inside VS Code.

I've also cracked open the 117.3 VSIX and see the code I re-added in #206.  Can you provide a screenshot of the status bar or the error message you're seeing?

**Comment by Rainson12** [comment]
if you are on windows, can you check if you are using double slashes in your settings.json? Like:
"tfvc.location": "C:\\Program Files (x86)\\TEE-CLC-14.114.0\\tf.cmd",

happend to me..

**Comment by tegaaa** [comment]
Yes I had a folder open.  I can’t give you a screenshot until next week, I’m at build this week.

**Comment by tegaaa** [comment]
Yes I had \\ in the cmd path.

**Comment by tegaaa** [comment]
I just install the 1.118.0 and I'm still seeting this.  Is there anywhere with a log with more info?  I tried on my own machine (I'm at a customer site) and it works fine.  So I'm not sure what's up with this machine?

[cid:329812ee-407e-43ee-9d36-5bc06387247a]


I do have the double slash \\ as you can see.

[cid:cd7f7a9e-3aeb-436d-89db-cca44484c1b3]


I click on the little team icon

[cid:1d43924a-c1ed-4942-9bd9-295c6f53c681]


I have it opened in a TFS folder

[cid:92d75995-344a-40d1-8274-f4ea52fa15b6]

________________________________

**Comment by jeffyoung** [comment]
Can you turn on [debug logging](https://github.com/Microsoft/vsts-vscode/blob/master/README.md#logging) and see if there's any interesting information in the log (provide it here)?

I see that you're using TF.exe with a French VS Code so perhaps our detection of the TFVC workspace isn't perfect (TF.exe will, by default, output in French on an OS configured with French UI). If the extension detected French output, you'd be getting an error similar to `It appears you have configured a non-English version of the TF executable. Please ensure an English version is properly configured.` Having the output of a `tf workfold` command would also be helpful.

Also, what can you say about the differences between the two machines (working and non-working)? If you're using the CLC on one of them, the CLC is set to always return English strings in its output. With TF.exe, you have to "force" it by not allowing it to find the proper resources (see #180) since you cannot tell it otherwise. If you're not able to fool TF.exe, you'll need to use the [CLC on Windows](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#how-do-i-set-up-the-clc-on-windows) (for non-English OSes).

**Comment by tegaaa** [comment]
you are correct I'm getting the error you stated. It appears you have configured a non-English version of the TF executable. Please ensure an English version is properly configured


TF Workfold

D:\TFS_Test\Debourses-38>tf workfold
===============================================================================
Espace de travail : xxx(Tremblay, Etienne)
Collection        : http://xxx:8080/tfs/defaultcollection
 $/Debourses-38: D:\TFS_Test\Debourses-38
 $/MainFrame: D:\TFS_Test\Mainframe


On is completely english-US (working one) the other is mostly french with some apps installed in english.


Output of log

2017-05-16T13:38:07.969Z - info:   [05448] *** FOLDER: d:\TFS_Test\Debourses-38 ***
2017-05-16T13:38:07.971Z - info:   [05448] version 1.118.0
2017-05-16T13:38:07.972Z - debug:  [05448] Looking for an External Context at d:\TFS_Test\Debourses-38
2017-05-16T13:38:07.973Z - debug:  [05448] No External Context at d:\TFS_Test\Debourses-38
2017-05-16T13:38:07.974Z - debug:  [05448] Looking for TFVC repository at d:\TFS_Test\Debourses-38
2017-05-16T13:38:07.975Z - debug:  [05448] TFVC Creating Tfvc object with localPath='undefined'
2017-05-16T13:38:07.975Z - debug:  [05448] Using TFS proxy: undefined
2017-05-16T13:38:07.976Z - debug:  [05448] TFVC Retrieved from settings; localPath='C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\TF.exe'
2017-05-16T13:38:07.976Z - debug:  [05448] TFVC Repository created with repositoryRootFolder='d:\TFS_Test\Debourses-38'
2017-05-16T13:38:07.977Z - debug:  [05448] TFVC Repository.CheckVersion
2017-05-16T13:38:07.978Z - debug:  [05448] TFVC: tf add -noprompt -?
2017-05-16T13:38:07.983Z - debug:  [05448] TFVC: spawned new process (duration: 4ms)
2017-05-16T13:38:07.987Z - debug:  [05448] TFVC: spawned new process (duration: 4ms)
2017-05-16T13:38:08.485Z - debug:  [05448] TFVC: add exit code: 0 (duration: 506ms)
2017-05-16T13:38:08.487Z - error:  [05448] It appears you have configured a non-English version of the TF executable. Please ensure an English version is properly configured.


ok after I "removed" the resource folder for Team Explorer, it works.  You guys need to make sure it works with othe languages...

________________________________

**Comment by jeffyoung** [comment]
Thanks @tegaaa. I'm glad you were able to figure out the issue.

I've got a story on our backlog to investigate how to make TF.exe work across languages since we have to parse the output from TF.exe to provide the functionality in VS Code. (TF.exe emits its output based on the language that's set up on the OS without a method to override it. The TEE CLC can be forced to emit English strings regardless of the OS settings and that's what we do in the extension.) This functionality will likely require an update to TF.exe itself so I don't know when we would get around to adding that support.  That said, I certainly appreciate the feedback.

Another potential workaround could be to install the "Team Explorer 2017" version of Visual Studio 2017, use the TF.exe which ships with that SKU and configure it for English. Then, you can use that version with VS Code while maintaining French in your Enterprise version (which is what you're currently using). You can find the Team Explorer 2017 version on the [Visual Studio Downloads](https://www.visualstudio.com/downloads/) page under the "Visual Studio 2017" section (which needs to be expanded first).

**Comment by tegaaa** [comment]
Indeed.  Glad I could help.


Cheers,

ET

________________________________
