### ISSUE TITLE
Feature Request: VSTS Build Status Notifications

### ISSUE THREAD

**Issue by eogas** [Microsoft/vsts-vscode#225]
Back in the day I used to use the bundled "Build Notifications" desktop app for XAML build definitions and it was awesome, however it was never updated to support the new VSTS build definitions.

The required VSTS APIs are certainly available to create a subscriber for build notifications, so while someone could write a desktop app to listen for these events (in fact, [someone already has](https://catlight.io/)), why not just integrate notifications into the editor via this extension?  Could be cool.

**Comment by jeffyoung** [comment]
The extension already polls for information regarding the build status for a particular repository and branch.  The information is [displayed in the status bar](https://github.com/Microsoft/vsts-vscode#status-bar-indicators). Another build status related issue is #146.

For Git, we call the server every polling interval asking for the build status for the current repository and branch.  If one exists, we display a different icon depending on that status (successful, failed). What I don't do yet is query for a build on the master branch assuming (a) you're not currently on master, and (b) there's no build in your current branch (e.g., a topic branch). If I did, you could also keep an eye on the master branch build when you aren't working in master and you don't have a build set up on your current branch (which might not be).

For TFVC, we get the latest 100 completed builds (excluding deleted) for a particular team project, order them by FinishTimeDescending, then find the first build whose repository type is "tfsversioncontrol". That build is used for the build status. If no builds are found, we'll render the default status. Clicking on the status bar item will either take you to the found build or the build definitions page.

We're limited in the type of "flash" we can provide due to what VS Code allows (no real changing of colors, popping up fly-out menus, etc., that I'm aware of).

I assume you were aware of the build status bar item but I'm curious as to what, in particular, you might be interested in seeing. (And, to be clear, I've made requests of the VS Code team for cool features like "fly-out" menus off of status bar items but... 😞 )

**Comment by eogas** [comment]
I think you've got the idea I'm thinking of.  The aspect of the old build notifications app that I really liked was the "toast" style notifications it would give you from the tray icon.

The only thing I know of that could provide something like this would be an info message on a timer, but that would probably not be a very good way of doing it.  I can imagine that it would be really annoying if you have a lot of automated builds running all the time, popping up info messages that cover up your tabs in the editor.

It does seem like this sort of feature would require an editor feature specifically for showing toast style notifications.  Thanks for the response.  I'll go ahead and close the issue.
