### ISSUE TITLE
Disable Team extension by workspace settings

### ISSUE THREAD

**Issue by Jkaveri** [Microsoft/vsts-vscode#23]
I'm working on a project with is using Git repo (It is not TFS repo). The visual studio code always shows message like this
![error msg](https://cloud.githubusercontent.com/assets/884709/16687264/b34aba38-4541-11e6-98ff-5e4f804273b3.png)

Are there any way to disable the extension for a project?

**Comment by jeffyoung** [comment]
AFAIK, VS Code extensions can be uninstalled but not disabled.  

Can you tell me more about the repository?  When you say it is using "Git" but "not TFS" is it a Team Services repository (that is, hosted on visualstudio.com)?  Have you already configured the extension by creating a personal access token (PAT) in order to access the server (according to the [instructions in the README.file](https://github.com/Microsoft/vsts-vscode/blob/master/README.md#install-the-extension))?  The extension requires a PAT in order to authenticate to the server to get data about pull requests, builds and work items.

If you've already configured it for a particular Team Services account, are you looking for a way to disable the extension for some other Team Services account?

Finally, if the Git repository is not on visualstudio.com, can you tell me more about where it is hosted?

**Comment by Jkaveri** [comment]
Hi @jeffyoung,

I have 2 projects:

1. A Git repo is hosted on my server (GitLab community version). 
2. A Git repo is hosted on {username}.visualstudio.com server.

I think we should have an option to disable the extension in a particular project workspace because we use the VSCode for multiple projects.

Thanks,

**Comment by jeffyoung** [comment]
Hi @Jkaveri.  Since this issue was opened, we've updated the extension quite a bit.  Now, I would suspect that if you open a folder for your Team Services repository, you'll be prompted to "sign in" and provide your personal access token.  I'd be interested in knowing if this changes what you've seen.

**Comment by jeffyoung** [comment]
Closing since there has been no follow-up.
