### ISSUE TITLE
Non-English version of the TF executable

### ISSUE THREAD

**Issue by Schlicki2808** [Microsoft/vsts-vscode#254]
Getting this message when trying to work with a TFS repository:

> (team) It appears you have configured a non-English version of the TF executable. Please ensure an English version is properly configured.

It should also be possible to use this extension on german systems.

**Comment by jeffyoung** [comment]
Hi @Schlicki2808.  Thanks for trying out the extension.

Unfortunately (in this case, anyway), tf.exe will send its output to stdout in the language that is configured for the operating system.  The VS Code extension relies on either TF.exe (or TF.cmd from the TEE CLC) to do all of the communication to the TFS server.  As such, the extension needs to parse the output and that can't be done for languages that translate more than English (it would be a large and bug-ridden undertaking).  Issues #177 and #180 have potential workarounds to the issue.  (I've considered adding support to TF.exe to optionally output all messages in English but haven't decided on that.  Even if it were to be implemented, it would only be available in a quarterly update and would require everyone to update to that version.)

Perhaps the workarounds will be useful to you?  That said, I'll add a "Frequently Asked Question" about it (since it is) on the TFVC page.  Also, if you don't want to affect your installed version of Visual Studio, you may be able to install the [Team Explorer 2017 version](https://github.com/Microsoft/vsts-vscode/blob/master/TFVC_README.md#how-can-i-acquire-tfexe-do-i-need-a-version-of-visual-studio) of the IDE and apply the workaround to that installation instead.

**Comment by jeffyoung** [comment]
Resolved in 1.119.1 (I added a clickable button when this message is received to take the user to more information about the issue).
