### ISSUE TITLE
Associate Work Items always shown, even when SCM Provider not VSTS

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vsts-vscode#262]
Open VS Code on a Git controlled project.
Install the VSTS extension
Without switching SCM providers, go to the Source Control view More ... dropdown.
"Associate Work Items" is displayed.

**Comment by jeffyoung** [comment]
Thanks for reporting @gregvanl.

This is a bit of a tricky scenario since you can also associate work items for VSTS/TFS **Git** repositories where the Git support is provided by VS Code (and not this extension).  The extension *does* supply the TFVC support which complicates matters even more.  So I'm trying to walk a tightrope between supporting the feature for VSTS/TFS **Git** repositories as well as **TFVC** repositories.

That said, the menu option also shows if the extension is installed and you either aren't using Git or TFVC (or, probably most likely, the Git repository just isn't a VSTS/TFS one). In that case, when you click the menu item, I attempt to show a message that indicates that fact:

![image](https://user-images.githubusercontent.com/2796865/27554370-312dd34a-5a7c-11e7-88dc-7e30cdb747d9.png)

I'd be interested in knowing if you saw that message or not.

Ideally, I could control whether or not the menu item was enabled/disabled (or even showing) if the extension detects that the repository isn't one it supports.  So in the case of a non-VSTS/TFS repo (TFVC or Git), the menu item just wouldn't appear or it would be disabled.  I don't think that support exists and I thought I opened a feature request on the VSCode repository for just such a feature.  I'll have to track it down.

So I'd like to know if you did see the message.  And if you have any suggestions for how to improve the experience, I'd be interested.  Thanks again!

**Comment by jeffyoung** [comment]
I guess I didn't have this specific issue filed so I added it to a similar one I did open previously.  It's at https://github.com/Microsoft/vscode/issues/23956.

**Comment by gregvanl** [comment]
@jeffyoung I do see the message. 
I think it might be less confusing to use the same when clause as the other Team commands `"when": "scmProvider == tfvc"`. The Associate Work Item command will still be available from the Command Palette. Right now it is displayed for all SCM Providers, even non-Git providers like Perforce or Mercury.

**Comment by jeffyoung** [comment]
Thanks @gregvanl.

I'll update it so it doesn't show on either Perforce or Mercurial.  While the extension still supports Git (those hosted on VSTS and TFS) I'm hesitant to remove it for all Git repositories.  Another useful feature might be to have [extension-specific menus](https://github.com/Microsoft/vscode/issues/365) (but that doesn't appear to be something we'll see). So I'm between a bit of a rock and a hard place.  😕

**Comment by jeffyoung** [comment]
Resolved in 1.119.1 (it will only show for TFVC and Git repositories).
