### ISSUE TITLE
Error:KEY_TF_BAD_EXIT_CODE error in android studio while cloning

### ISSUE THREAD

**Issue by akeditzz** [Microsoft/vsts-vscode#275]
hi guys, when i try to update my project from the repository in android studio, i am getting this error,
i have cross checked all the setup its all fine, what is causing to get this error, 
Please help

Visual Studio Team Service,  version: 1.120.0

**Comment by jeffyoung** [comment]
Hi @akeditzz.  I see that you opened the [same issue](https://github.com/Microsoft/vso-intellij/issues/87) against the intellij repository (and referenced version 1.120.0 of the extension).  I wanted to clarify that this issue is one you're seeing with IntelliJ (and are investigating it there) as I haven't yet released 1.120.0 of the VS Code extension. If so, we can go ahead and close this one.
