### ISSUE TITLE
Do not see in documentation how to connect to existing TFS

### ISSUE THREAD

**Issue by yurybond** [Microsoft/vsts-vscode#44]
MacOS, Visual Studio Core, Visual Studio Code + Visual Studio Team Services plugin

When trying to execute command line
`team login`

in VC Code it returns:

> (team) No Team Services or Team Foundation Server Git repository configuration was found. Ensure you've opened a folder that contains

<img width="909" alt="error_message_tfs" src="https://cloud.githubusercontent.com/assets/563683/17447817/930f2bd0-5b05-11e6-9c10-0a4da2a937aa.png">

1. What exact configuration is required? Can I checkout project code with "VS Code + VS TS plugin"?
1. Can I checkout from TFVC (no Git) using  "VS Code + VS TS plugin"?

**Comment by jeffyoung** [comment]
Hi Yury.  Thanks for trying out the extension.

The extension only supports Git repositories at this time (and not TFVC).  TFVC is on the backlog but we haven't gotten there yet.

Can you tell me a bit more about how you discovered the extension and where I might be able to add pointers to the documentation?  v1.3 of VS Code brought in the Extensions viewlet and changed the acquisition experience a little bit (and I think I could use some improvement in the scenario where folks acquire it that way).

**Comment by yurybond** [comment]
Hi Jeff, 
Thank you for quick response. I used README.MD to setup a connection from "Code" to TFS. Also tried to search in google about your plugin and can find anything about "Git only" limitation.

In terms of README.md everything is perfect,  seriously, but section Authentication is a bit confusing for me (sorry I do not have much experience in TFS).

1. Could you somewhere highlight that having of git repository is must to setup a connection?
2. Also, In Authentication section you explain how to obtain token and other helpful details but authentication process itself is not described. We can see 'team login' in next section named 'Open a local Git Repository folder'. 

![auth](https://cloud.githubusercontent.com/assets/563683/17450398/c36678a6-5b14-11e6-8b43-533b9c990566.png)

Thank you

**Comment by jeffyoung** [comment]
Thanks for the information Yury.  I’m always looking for ways to make things easier to do and easier to understand.

Regarding only supporting Git repositories, I can certainly understand how it can be confusing.  Basically, the documentation only ever refers to Git and doesn't explicitly state that there isn't any support for TFVC. In the extension description and the first paragraph I mention Git but I don't make it explicit that there isn't any support for TFVC.

Regarding the Authentication Git repos section, I'll make some updates there to make it more plain about where you'll use your credentials.  For the git repositories, I assumed that your repository would already be cloned (since VS Code doesn't provide a way to clone from within it).  I'll make that more plain.  (In addition, I recently added support to detect when a repository was newly pushed to a VSTS account.  See #27.)

I'll make some changes soon and get out a PR.  Hopefully the changes I make will make it easier to understand.

**Comment by yurybond** [comment]
Thank you Jeff, 

P.S.
Do you have an idea when TFVC support will be included to the extension?

**Comment by jeffyoung** [comment]
Hi Yury.

Unfortunately, I don't have an ETA yet on the TFVC support.  Once it is available (in any form), I'll make sure it gets announced.

I also just merged #45 to improve the documentation and help users get to success.  Thanks again for providing your feedback!
