### ISSUE TITLE
Work items from visualstudio.com should not be visiblewhen they are in a resolved or fixed state.

### ISSUE THREAD

**Issue by cj13579** [Microsoft/vsts-vscode#57]
I think that the item is visible in vscode because there is no filter on the list and it is showing all items that are assigned to me (as per the notes in the README) but it makes it seem like there are many more outstanding bugs on an application than there really are.

![vs-code-resolved](https://cloud.githubusercontent.com/assets/1965454/19686520/ddabf9bc-9a97-11e6-9244-fb3e41dda645.png)

![bug1_vs_resolved](https://cloud.githubusercontent.com/assets/1965454/19686529/e3d6c466-9a97-11e6-9fd3-108c1cb3f3a7.png)

**Comment by jeffyoung** [comment]
Hi Christopher.  Thanks for trying out the extension!

Have you see the ability to provide your own query (a [pinned query](https://github.com/Microsoft/vsts-vscode#pinned-work-item-queries)) in the User Settings?   You can write whatever query you want and it'll use it as the default to show in the status bar.

**Comment by cj13579** [comment]
Ah-ha, I didn't see that. I've created a query "OpenItems" under "My Queries" but I can't seem to get is to come through to vscode. Perhaps I am doing something incorrectly? I have the following in my settings.json:

```json
{
    "team.pinnedQueries": [
        {
            "account": "account.visualstudio.com",
            "queryPath": "My Queries/OpenItems"
        }
    ]

}
```

**Comment by jeffyoung** [comment]
Can you be a bit more specific by what you mean regarding that you "can't seem to get it to come through"?

If the query can't be found, you'll get an error message with a 404.  Is that what you get?  Otherwise, if it can find the query, it should run it and display the count on the status bar.  When clicking on the status bar, the QuickPick menu will open and display the results of the query.  If there are > 200 items, only 200 will be shown with an additional item that will take you to the query results in the web.  If there's more than the server max (~20,000), you'll get a different error.  Or is it not showing you the results that you expect?

**Comment by cj13579** [comment]
It was my bad again. I didn't have my account specified correctly. I am now seeing what I expect. I'll close this issue now.

Thanks for the help.
