### ISSUE TITLE
Ability to select a 'Team' under a 'Project'

### ISSUE THREAD

**Issue by slx2005** [Microsoft/vsts-vscode#60]
As a large organisation, we have a lot of projects running in TFS, so the ability to 'focus' in on a certain team / project would be great, this way we could see only our teams PBI's Bugs etc, and recognize our builds.

And the look of 994 bugs kinda scares me a little...
![image](https://cloud.githubusercontent.com/assets/585373/19968379/3a99b9bc-a1cc-11e6-897e-59cf616e7b4e.png)

**Comment by jeffyoung** [comment]
Hi Louis.  Thanks for trying out the extension!

You have some control over what will be displayed with regards to the bug count appearing in the status bar.  You can set your own "pinned query" in the User Settings (see #57 for more details) and provide either your own wiql query or path to an existing query.  So long as it points to valid wiql, it'll be executed and the count will show up in the status bar.  Otherwise, it simply defaults to whatever is assigned to you.

The build that shows up is for the current repo and branch (although I'd like to change this at some point so that if the current branch doesn't have a build associated with it, it would search for a build on the default (master) branch instead.  In that way, you can be working in your feature/topic branch and get notified if the master branch build gets broken.  Today, it just looks for the latest build on the current branch.  So if you aren't in master, you don't know the state of master's build... and you might not have a build definition set up for your feature/topic branch.)

The PR status item shows whatever is assigned to (or created by) you (which I think is what you'd want).  

Hopefully having a "pinned query" that you can control will give you the results of what you're looking for.  If not, please LMK.

**Comment by slx2005** [comment]
The pinned query did work, thanks for the information and quick reply.
